---
all:
  children:
    local:
      hosts:
        myserver-local:
          ansible_host: 192.168.1.163
    tailscale:
      hosts:
        myserver-tailscale:
          ansible_host: 100.99.9.7

# Proxmox Tailscale = 100.74.253.105
# Proxmox Local = 192.168.0.100
